# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\EventListener\anneeScolairesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\AnneeScolaires'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\AnneeScolaires'}    # add more service definitions when explicit configuration is needed
    App\EventListener\cerclesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Cercles'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Cercles'}    # add more service definitions when explicit configuration is needed
    App\EventListener\classesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Classes'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Classes'}    # add more service definitions when explicit configuration is needed
    App\EventListener\communesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Communes'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Communes'}    # add more service definitions when explicit configuration is needed
    App\EventListener\contratsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Contrats'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Contrats'}    # add more service definitions when explicit configuration is needed
    App\EventListener\cyclesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Cycles'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Cycles'}    # add more service definitions when explicit configuration is needed
    App\EventListener\departementsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Departements'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Departements'}    # add more service definitions when explicit configuration is needed
    App\EventListener\ecoleProvenancesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\EcoleProvenances'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\EcoleProvenances'}    # add more service definitions when explicit configuration is needed
    App\EventListener\enseignementsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Enseignements'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Enseignements'}    # add more service definitions when explicit configuration is needed
    App\EventListener\etablissementsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Etablissements'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Etablissements'}    # add more service definitions when explicit configuration is needed
    App\EventListener\lieuNaissancesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\LieuNaissances'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\LieuNaissances'}    # add more service definitions when explicit configuration is needed
    App\EventListener\niveauEtudesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\NiveauEtudes'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\NiveauEtudes'}    # add more service definitions when explicit configuration is needed
    App\EventListener\niveauxEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Niveaux'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Niveaux'}    # add more service definitions when explicit configuration is needed
    App\EventListener\nomsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Noms'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Noms'}    # add more service definitions when explicit configuration is needed
    App\EventListener\periodicitesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Periodicites'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Periodicites'}    # add more service definitions when explicit configuration is needed
    App\EventListener\personnelsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Personnels'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Personnels'}    # add more service definitions when explicit configuration is needed
    App\EventListener\prenomsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Prenoms'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Prenoms'}    # add more service definitions when explicit configuration is needed
    App\EventListener\professionsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Professions'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Professions'}    # add more service definitions when explicit configuration is needed
    App\EventListener\regionsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Regions'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Regions'}    # add more service definitions when explicit configuration is needed
    App\EventListener\specialitesEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Specialites'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Specialites'}    # add more service definitions when explicit configuration is needed
    App\EventListener\statutsEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Statuts'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Statuts'}    # add more service definitions when explicit configuration is needed
    App\EventListener\usersEntityListener:
            tags:
                - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'App\Entity\Users'}
                - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Entity\Users'}    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
